version: "{branch}.{build}"
image:
  - "Visual Studio 2015"
cache:
  - "%USERPROFILE%\\.gradle\\wrapper\\dists"
  - "%USERPROFILE%\\.gradle\\caches\\jars-3"
  - "%USERPROFILE%\\.gradle\\caches\\modules-2"
  - "%USERPROFILE%\\.gradle\\caches\\sphinx-binary"
init:
  - git config --global core.autocrlf true
build:
  verbosity: detailed
build_script:
  - 'gradlew.bat --no-daemon clean build site'
test: off
matrix:
  fast_finish: true
